const WORKOUT_KEY='vk_workout_log_v1';
const IMG='https://exercise-dataset.com/images/flat/';
const W={
1:{name:'Full Body A',focus:'Temel kuvvet • kontrollü tempo',ex:[
['Goblet Squat','Bacak • kalça',3,'8–12','goblet-squat','squat'],
['Dambıl Bench Press','Göğüs • ön omuz • triceps',3,'8–12','db-bench-press','press'],
['Tek Kol Dambıl Row','Sırt • arka omuz • biceps',3,'8–12/kol','single-arm-db-row','row'],
['Dambıl Romanian Deadlift','Arka bacak • kalça',2,'8–12','dumbbell-romanian-deadlift','hinge'],
['Hammer Curl','Biceps • ön kol',2,'10–12','hammer-curl','curl']]},
2:{name:'Full Body B',focus:'Çekiş • omuz • tek taraflı bacak',ex:[
['Destekli Split Squat','Bacak • kalça',3,'8–10/kol','dumbbell-split-squat','squat'],
['Eğimli Dambıl Press','Üst göğüs • omuz • triceps',3,'8–12','incline-db-press','press'],
['Bench Destekli Dambıl Row','Sırt • arka omuz',3,'10–12','single-arm-chest-supported-dumbbell-row','row'],
['Bench Glute Bridge','Kalça • arka bacak',3,'10–15','glute-bridge','bridge'],
['Oturarak Dambıl Shoulder Press','Omuz • triceps',2,'8–12','seated-db-press','press']]},
3:{name:'Full Body C',focus:'Hareket kalitesi • omuz • core',ex:[
['Dambıl Front Squat','Bacak • kalça • core',3,'8–12','dumbbell-front-squat','squat'],
['Dambıl Floor Press','Göğüs • triceps',3,'8–12','dumbbell-floor-press','press'],
['Bench Destekli Rear-Delt Row','Arka omuz • üst sırt',2,'10–15','rear-delt-fly','row'],
['Lateral Raise','Yan omuz',2,'10–15','lateral-raise','raise'],
['Dead Bug','Core',2,'8–10/yan','dead-bug','core']]}}
let S=load();let day=1;let selected=null;let active=false;let timerId=null;let sessionStartedAt=0;let elapsed=0;
function load(){try{const x=JSON.parse(localStorage.getItem(WORKOUT_KEY))||{};return{logs:Array.isArray(x.logs)?x.logs:[],weights:x.weights||{},done:x.done||{},session:x.session||null}}catch(e){return{logs:[],weights:{},done:{},session:null}}}
function saveWorkoutState(){localStorage.setItem(WORKOUT_KEY,JSON.stringify(S))}
function today(){return new Date().toISOString().slice(0,10)}
function key(id){return day+'_'+id}
function detailsFor(name){const log=(S.logs||[]).find(x=>x.date===today()&&x.day===day&&x.exercise===name);if(Array.isArray(log?.setDetails)&&log.setDetails.length)return log.setDetails.map(s=>({weight:+s.weight||0,reps:+s.reps||10}));return log?[{weight:+log.weight||0,reps:+log.reps||10}]:[]}
function kcalFor(details){const bw=109;return Math.max(3,Math.round(details.reduce((sum,s)=>{const r=Math.max(1,+s.reps||10),w=Math.max(0,+s.weight||0),load=1+(w/bw)*1.8,vol=1+(w*r)/(bw*40);return sum+r*.18*Math.min(2.2,load)*Math.min(2.2,vol)},0)))}
function volumeFor(details){return Math.round(details.reduce((s,x)=>s+(+x.weight||0)*(+x.reps||10),0))}
function repsLabel(details,planned){if(!details.length)return planned.replace('–','-');const a=details.map(x=>+x.reps||0);return a.every(x=>x===a[0])?String(a[0]):'farklı'}
function allTodayLogs(){return(S.logs||[]).filter(x=>x.date===today()&&x.day===day)}
function workoutKcal(){return allTodayLogs().reduce((s,l)=>s+kcalFor(Array.isArray(l.setDetails)&&l.setDetails.length?l.setDetails:[{weight:l.weight,reps:l.reps}]),0)}
function totalSets(){return allTodayLogs().reduce((s,l)=>s+(Array.isArray(l.setDetails)&&l.setDetails.length?l.setDetails.length:(+l.sets||0)),0)}
function syncDashboard(){try{if(typeof state==='undefined'||typeof save!=='function')return;const prev=(state.dailySports||[]).find(x=>x.workoutDay===day&&x.date===today());const kcal=workoutKcal();if(prev)state.burned=Math.max(0,state.burned-(+prev.calories||0));if(kcal){const item={name:'Ağırlık Antrenmanı',duration:Math.round(elapsed/60),calories:kcal,workoutDay:day,date:today(),sessionId:S.session?.id||null};state.dailySports=(state.dailySports||[]).filter(x=>!(x.workoutDay===day&&x.date===today()));state.dailySports.push(item);state.burned+=kcal}else{state.dailySports=(state.dailySports||[]).filter(x=>!(x.workoutDay===day&&x.date===today()))}save();if(typeof updateDashboard==='function')updateDashboard()}catch(e){}}
function initWorkout(){if(!document.getElementById('workoutPage'))return;tabs();render();history();document.getElementById('workoutDayTabs').onclick=e=>{const b=e.target.closest('[data-day]');if(!b)return;day=+b.dataset.day;tabs();render()};document.getElementById('workoutDetail').onclick=e=>{const openBtn=e.target.closest('[data-open]');if(openBtn)open(+openBtn.dataset.open);const plus=e.target.closest('[data-add-set]');if(plus)addSetFromCard(+plus.dataset.addSet);const done=e.target.closest('[data-done]');if(done)completeExercise(+done.dataset.done)};document.getElementById('workoutModal').onclick=e=>{if(e.target.id==='workoutModal'||e.target.matches('[data-close]'))close();if(e.target.matches('[data-save-exercise]'))log()};['workoutWeight','workoutSetsDone','workoutRepsDone'].forEach(id=>document.getElementById(id).oninput=preview)}
function tabs(){document.getElementById('workoutDayTabs').innerHTML=[1,2,3].map(d=>'<button class="workout-day '+(d===day?'active':'')+'" data-day="'+d+'"><strong>Gün '+d+'</strong><span>'+W[d].name.replace('Full Body ','')+'</span></button>').join('')}
function startSession(){if(active)return;active=true;sessionStartedAt=Date.now()-elapsed*1000;S.session={id:String(Date.now()),day};saveWorkoutState();renderActive();tick()}
function pauseSession(){active=false;clearInterval(timerId);elapsed=Math.max(0,Math.round((Date.now()-sessionStartedAt)/1000));renderActive();saveWorkoutState()}
function finishSession(){elapsed=Math.max(0,Math.round((Date.now()-sessionStartedAt)/1000));active=false;clearInterval(timerId);S.session=null;syncDashboard();saveWorkoutState();renderActive();render();history()}
function tick(){clearInterval(timerId);timerId=setInterval(()=>{if(!active)return;elapsed=Math.max(0,Math.round((Date.now()-sessionStartedAt)/1000));renderActive();updateStats()},1000)}
function fmt(sec){return String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
function renderActive(){const p=document.getElementById('activeWorkoutPanel');if(!p)return;const title=active?'Antrenmana Devam Ediyor':'Antrenmana Hazır';const sub=active?'Süreyi takip et ve setlerini kaydet':'Başla, setlerini tek tek kaydet ve sonunda antrenmanı tamamla.';p.innerHTML='<div class="workout-active"><div class="active-top"><div class="play-circle">'+(active?'▶':'▶')+'</div><div class="active-copy"><strong>'+title+'</strong><span>'+sub+'</span></div><div class="active-time">'+fmt(elapsed)+'<small>Süre</small></div></div><div class="active-actions"><button id="pauseWorkout">'+(active?'Durdur':'Antrenmanı Başlat')+'</button><button class="finish" id="finishWorkout">Antrenmanı Tamamla</button></div></div>';document.getElementById('pauseWorkout').onclick=()=>active?pauseSession():startSession();document.getElementById('finishWorkout').onclick=finishSession}
function addSetFromCard(i){const x=W[day].ex[i],k=key(x[0]);const w=+document.querySelector('[data-weight="'+i+'"]')?.value||0;const r=+document.querySelector('[data-reps="'+i+'"]')?.value||10;const details=detailsFor(x[0]);details.push({weight:w,reps:r});S.logs=(S.logs||[]).filter(l=>!(l.date===today()&&l.day===day&&l.exercise===x[0]));S.logs.unshift({date:today(),at:Date.now(),day,exercise:x[0],weight:w,sets:details.length,reps:r,rpe:7,setDetails:details,sessionId:S.session?.id||null});if(w)S.weights[k]=w;S.done[k]=false;saveWorkoutState();syncDashboard();render();history()}
function completeExercise(i){const x=W[day].ex[i],k=key(x[0]);let details=detailsFor(x[0]);if(!details.length){const w=+document.querySelector('[data-weight="'+i+'"]')?.value||+S.weights[k]||0;const r=+document.querySelector('[data-reps="'+i+'"]')?.value||parseInt(x[3])||10;details=Array.from({length:x[2]},()=>({weight:w,reps:r}))}S.logs=(S.logs||[]).filter(l=>!(l.date===today()&&l.day===day&&l.exercise===x[0]));S.logs.unshift({date:today(),at:Date.now(),day,exercise:x[0],weight:details[0].weight,sets:details.length,reps:details[0].reps,rpe:7,setDetails:details,sessionId:S.session?.id||null});if(details[0].weight)S.weights[k]=details[0].weight;S.done[k]=S.done[k]===today()?false:today();saveWorkoutState();syncDashboard();render();history()}
function render(){const w=W[day].ex,done=w.filter(x=>S.done[key(x[0])]===today()).length;document.getElementById('workoutTitle').textContent=w.name;document.getElementById('workoutSubtitle').textContent=W[day].focus;document.getElementById('workoutProgress').textContent=done+'/'+w.length;document.getElementById('workoutDetail').innerHTML=w.map((x,i)=>{const k=key(x[0]),ok=S.done[k]===today(),details=detailsFor(x[0]),last=details[details.length-1],wt=last?.weight||S.weights[k]||'',reps=last?.reps||parseInt(x[3])||10,sets=details.length||0,kcal=kcalFor(details),vol=volumeFor(details);return '<article class="exercise-card '+(ok?'done':'')+'"><div class="exercise-image"><img loading="lazy" src="'+IMG+x[4]+'-start.webp" alt="'+x[0]+'"></div><div class="exercise-body"><div class="exercise-title-row"><h3>'+x[0]+'</h3><div class="exercise-buttons"><button class="plus-btn" data-add-set="'+i+'" aria-label="Set ekle">+</button><button class="done-btn" data-done="'+i+'" aria-label="Hareketi tamamla">✓</button></div></div><div class="exercise-fields"><label>Ağırlık<input data-weight="'+i+'" type="number" min="0" step="0.5" value="'+wt+'"></label><label>Set<input data-sets="'+i+'" type="number" min="0" value="'+(sets||x[2])+'"></label><label>Tekrar<input data-reps="'+i+'" type="number" min="1" value="'+reps+'"></label></div><div class="exercise-results"><span>🔥 '+kcal+' kcal</span><span>🏋️ '+vol+' kg</span><span>▱ '+(sets||x[2])+' set</span></div><button class="technique-btn" data-open="'+i+'">▶ Nasıl yapılır?</button></div></article>'}).join('');updateStats()}
function updateStats(){const w=W[day].ex,done=w.filter(x=>S.done[key(x[0])]===today()).length;document.getElementById('workoutMoveCount').textContent=done+' / '+w.length;document.getElementById('workoutSetCount').textContent=totalSets();document.getElementById('workoutDuration').textContent=Math.round(elapsed/60)+' dk';document.getElementById('workoutKcal').textContent=workoutKcal()+' kcal'}
function open(i){selected=W[day].ex[i];const k=key(selected[0]),details=detailsFor(selected[0]);document.getElementById('workoutModalTitle').textContent=selected[0];document.getElementById('workoutModalMuscle').textContent=selected[1];document.getElementById('workoutAnimation').innerHTML='<img src="'+IMG+selected[4]+'-start.webp" style="width:170px;height:140px;object-fit:cover;border-radius:14px" alt="'+selected[0]+'">';document.getElementById('workoutCues').innerHTML='<li>Hareketi kontrollü ve rahat tempoda yap.</li><li>Omurgayı nötr tut ve nefesi tutma.</li><li>Son tekrarı da temiz teknikle tamamla.</li>';document.getElementById('workoutMistakes').innerHTML='<li>Ağırlığı savurma.</li><li>Eklem pozisyonunu zorlamama.</li>';document.getElementById('workoutSource').innerHTML='<a target="_blank" rel="noopener" href="https://exercise-dataset.com/exercise/'+selected[4]+'/">RepDB ↗</a>';document.getElementById('workoutWeight').value=details.at(-1)?.weight||S.weights[k]||'';document.getElementById('workoutSetsDone').value=details.length||selected[2];document.getElementById('workoutRepsDone').value=details.at(-1)?.reps||parseInt(selected[3])||10;preview();document.getElementById('workoutModal').classList.add('open')}
function preview(){document.getElementById('modalVolume').textContent=(+document.getElementById('workoutWeight').value||0)*(+document.getElementById('workoutRepsDone').value||0)||'—';document.getElementById('modalSets').textContent=document.getElementById('workoutSetsDone').value||'—';document.getElementById('modalReps').textContent=document.getElementById('workoutRepsDone').value||'—'}
function log(){if(!selected)return;const wt=+document.getElementById('workoutWeight').value||0,sets=+document.getElementById('workoutSetsDone').value||selected[2],reps=+document.getElementById('workoutRepsDone').value||parseInt(selected[3])||10,k=key(selected[0]);const details=Array.from({length:sets},()=>({weight:wt,reps}));S.logs=(S.logs||[]).filter(l=>!(l.date===today()&&l.day===day&&l.exercise===selected[0]));S.logs.unshift({date:today(),at:Date.now(),day,exercise:selected[0],weight:wt,sets,reps,rpe:+document.getElementById('workoutRpe').value||7,setDetails:details,sessionId:S.session?.id||null});if(wt)S.weights[k]=wt;S.done[k]=today();saveWorkoutState();syncDashboard();close();render();history()}
function close(){document.getElementById('workoutModal').classList.remove('open');selected=null}
function history(){const box=document.getElementById('workoutHistory');box.innerHTML=(S.logs||[]).slice(0,15).map(x=>'<div class="workout-history-item"><strong>'+new Date(x.date+'T12:00:00').toLocaleDateString('tr-TR')+'</strong><span>Gün '+x.day+' • '+x.exercise+'</span><span>'+x.sets+' set • '+x.weight+' kg • '+x.reps+' tekrar</span></div>').join('')||'<div class="empty-state">Henüz kayıt yok.</div>'}
document.addEventListener('DOMContentLoaded',initWorkout);
